# Generated by Django 3.0.2 on 2021-05-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('login', models.CharField(max_length=64)),
                ('job_title', models.CharField(max_length=64)),
                ('work_email', models.CharField(blank=True, max_length=128, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('department', models.CharField(max_length=128)),
                ('department_id', models.CharField(max_length=256)),
                ('department_ids', models.CharField(max_length=256)),
                ('path', models.URLField(max_length=256)),
                ('picture_url', models.URLField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(max_length=64)),
                ('organization', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('work_schedule', models.CharField(max_length=64)),
                ('department_titles', models.CharField(blank=True, max_length=256, null=True)),
                ('ct_id', models.CharField(blank=True, max_length=128, null=True)),
                ('hide', models.IntegerField()),
                ('doc_id', models.IntegerField()),
                ('path_dep', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
