# Generated by Django 3.0.2 on 2021-05-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0002_auto_20210517_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdepartment',
            name='create',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcdepartment',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
