# Generated by Django 3.0.2 on 2021-05-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0005_auto_20210519_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdepartment',
            name='parent_id',
            field=models.IntegerField(blank=True),
        ),
    ]
