# Generated by Django 3.0.2 on 2021-05-19 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0008_auto_20210519_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcdepartment',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='dcdepartment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_center.DCDepartment'),
        ),
    ]
