# Generated by Django 3.0.2 on 2021-06-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0009_auto_20210519_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdepartment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='data_center.DCDepartment'),
        ),
        migrations.AlterField(
            model_name='dcdepartment',
            name='users_count',
            field=models.IntegerField(default=0),
        ),
    ]
