# Generated by Django 3.0.2 on 2021-08-10 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('fio', models.CharField(max_length=128, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Имейл')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.CharField(max_length=512, verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фейковый запрос',
                'verbose_name_plural': 'Фейковые запросы',
            },
        ),
    ]
