# Generated by Django 3.0.2 on 2021-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_requests', '0002_auto_20210820_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер телефона'),
        ),
    ]
