# Generated by Django 3.0.2 on 2021-01-08 23:02

import apps.news.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=24)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PharmMarketArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('entity', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('portal_id', models.IntegerField(db_index=True, unique=True)),
                ('publish_date', models.DateTimeField()),
                ('is_main', models.BooleanField(default=False)),
                ('published', models.BooleanField(blank=True, default=True)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=apps.news.models.directory_path)),
                ('tags', models.ManyToManyField(related_name='pharm_market_articles', to='news.Tag', verbose_name='news_tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('entity', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('portal_id', models.IntegerField(db_index=True, unique=True)),
                ('publish_date', models.DateTimeField()),
                ('is_main', models.BooleanField(default=False)),
                ('published', models.BooleanField(blank=True, default=True)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=apps.news.models.directory_path)),
                ('tags', models.ManyToManyField(related_name='company_articles', to='news.Tag', verbose_name='news_tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
