# Generated by Django 3.0.2 on 2021-10-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210629_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='department',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='email',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='birthday',
            name='position',
        ),
        migrations.AddField(
            model_name='birthday',
            name='job_title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthday',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
