# Generated by Django 3.0.2 on 2021-10-07 08:39

import apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211006_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.news.models.directory_path),
        ),
    ]
