# Generated by Django 3.0.2 on 2021-10-07 08:54

import apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20211007_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelchange',
            name='date',
        ),
        migrations.RemoveField(
            model_name='personnelchange',
            name='number',
        ),
        migrations.AddField(
            model_name='personnelchange',
            name='announce',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelchange',
            name='image_prev',
            field=models.ImageField(null=True, upload_to=apps.news.models.directory_path),
        ),
        migrations.AddField(
            model_name='personnelchange',
            name='is_top',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelchange',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='personnelchange',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnelchange',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.news.models.directory_path),
        ),
        migrations.AlterField(
            model_name='personnelchange',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
