# Generated by Django 3.0.2 on 2021-10-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20211007_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelchange',
            name='announce',
            field=models.CharField(max_length=512),
        ),
    ]
