# Generated by Django 3.0.2 on 2021-01-07 13:07

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201221_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user.models.directory_path, verbose_name='Аватар'),
        ),
    ]
