# Generated by Django 3.0.2 on 2021-01-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharm_id', models.UUIDField(verbose_name='ID в фармсэде')),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fio', models.CharField(blank=True, max_length=128, null=True, verbose_name='Инициалы')),
                ('userstate', models.CharField(blank=True, max_length=256, null=True)),
                ('phone1', models.CharField(blank=True, max_length=64, null=True)),
                ('phone2', models.CharField(blank=True, max_length=64, null=True)),
                ('firm', models.CharField(blank=True, max_length=256, null=True)),
                ('depart', models.CharField(blank=True, max_length=256, null=True)),
                ('empl', models.CharField(blank=True, max_length=256, null=True)),
                ('abs_reason', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
