# Generated by Django 3.0.2 on 2021-01-18 11:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_pharmuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Пример, +79510549236', max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
