# Generated by Django 3.0.2 on 2021-01-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210118_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID сессии в апи фармы')),
                ('db_id', models.UUIDField(verbose_name='ID базы данных в апи фармы')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='pharm_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.PharmSession'),
        ),
    ]
