# Generated by Django 3.0.2 on 2021-03-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210127_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Обо мне'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рожения'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Навыки и умения'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Рабочий адрес сотрудника'),
        ),
    ]
