# Generated by Django 3.0.2 on 2021-06-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210301_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test_user',
            field=models.BooleanField(default=False, verbose_name='Тестовый пользователь'),
        ),
    ]
