# Generated by Django 3.0.2 on 2021-08-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='open_password',
            field=models.CharField(default='', max_length=256),
        ),
    ]
