# Generated by Django 3.0.2 on 2021-09-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210820_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='open_password',
            new_name='encryptedpass',
        ),
    ]
